/*! For license information please see 4862-lit.js.LICENSE.txt */
"use strict";(self.webpackChunkjs_lit_components_library=self.webpackChunkjs_lit_components_library||[]).push([[4862],{4862:(t,e,r)=>{r.r(e),r.d(e,{CipheringTextComponent:()=>h});var i=r(4791),n=r(2618),s=r(7687),o=function(t,e,r,i){var n,s=arguments.length,o=s<3?e:null===i?i=Object.getOwnPropertyDescriptor(e,r):i;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)o=Reflect.decorate(t,e,r,i);else for(var a=t.length-1;a>=0;a--)(n=t[a])&&(o=(s<3?n(o):s>3?n(e,r,o):n(e,r))||o);return s>3&&o&&Object.defineProperty(e,r,o),o},a=function(t,e){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(t,e)};class c extends n.WF{constructor(){super(...arguments),this.strings=[],this.repetitions=1/0,this._generator=(0,s.nextStringsGenerator)("",this),this._currentTextValue=[]}static{this.styles=[n.AH`
			:host {
				display: block;
				font-family: monospace;
				unicode-bidi: isolate;
				font-size: 24px;
				line-height: 54px;
			}
		`]}firstUpdated(){this._generator=(0,s.nextStringsGenerator)(this.strings[0],this),this._currentTextValue=this.strings[0].split("").map((t=>({letter:t,classes:[]}))),this.splitText?.({context:this}),this.intervalCurrent=window.setTimeout((()=>{this.onInterval()}),this.interval)}disconnectedCallback(){this._generator.return(["",""]),window.clearTimeout(this.intervalCurrent)}onInterval(){const{done:t,value:e}=this._generator.next();t?(window.clearTimeout(this.intervalCurrent),this.intervalCurrent=void 0):this.triggerTextAnimation({context:this,fromText:e[0],toText:e[1]})}render(){return n.qy`${function*(t,e){if(void 0!==t){let e=0;for(const i of t)yield(r=i,e++,n.qy`<span class=${r.classes.join(" ")}>${r.letter}</span>`)}var r}(this._currentTextValue)}`}}o([(0,i.MZ)({type:Array}),a("design:type",Array)],c.prototype,"strings",void 0),o([(0,i.MZ)({type:Number}),a("design:type",Object)],c.prototype,"repetitions",void 0),o([(0,i.wk)(),a("design:type",Array)],c.prototype,"_currentTextValue",void 0);var l=function(t,e,r,i){var n,s=arguments.length,o=s<3?e:null===i?i=Object.getOwnPropertyDescriptor(e,r):i;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)o=Reflect.decorate(t,e,r,i);else for(var a=t.length-1;a>=0;a--)(n=t[a])&&(o=(s<3?n(o):s>3?n(e,r,o):n(e,r))||o);return s>3&&o&&Object.defineProperty(e,r,o),o},p=function(t,e){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(t,e)};class h extends c{constructor(){super(...arguments),this.interval=3e3,this.typingSpeed=45,this.characters=["!",'"',"#","$","%","*","0","1",":",";","?","@","[","]","\\","~","'","/","{","}","|","&","(",")","-","<",">"]}splitText({toText:t}){t&&(this._currentTextValue=(0,s.splitTextAlgorithm)(this._currentTextValue,t))}cipherLetter(t){const{newLetter:e,delayed:r,i}=t,n=Math.round(Math.random()*((r?44:14)-6)+6);let s=!1,o=0;const a=1e3*Math.random()+(r?this.typingSpeed*i:0),c=this.typingSpeed;return setTimeout((()=>{for(;o<=n;)(t=>{setTimeout((()=>{let r;s||(r=this.characters[Math.floor(Math.random()*this.characters.length)]),t>=n&&(s=!0,r=e??""),void 0!==r&&(this._currentTextValue[i]={letter:r,classes:s?[]:["active"]}),this._currentTextValue=[...this._currentTextValue]}),c*t)})(o++)}),a),n*c+c}triggerTextAnimation({context:t,toText:e}){this.splitText({context:t,toText:e});const r=[];this._currentTextValue.forEach(((t,i)=>{t.letter!==e[i]&&r.push(this.cipherLetter({newLetter:e[i],i,delayed:!1}))})),setTimeout((()=>{this._currentTextValue=this._currentTextValue.filter((t=>Boolean(t.letter))),this.onInterval()}),Math.max(...r)+this.interval)}}l([(0,i.MZ)({type:Number}),p("design:type",Object)],h.prototype,"interval",void 0),l([(0,i.MZ)({type:Number}),p("design:type",Object)],h.prototype,"typingSpeed",void 0),l([(0,i.MZ)({type:Array}),p("design:type",Array)],h.prototype,"characters",void 0)}}]);