/*! For license information please see 5236-lit.js.LICENSE.txt */
"use strict";(self.webpackChunkjs_lit_components_library=self.webpackChunkjs_lit_components_library||[]).push([[5236],{5236:(t,e,r)=>{r.r(e),r.d(e,{RebuildingTextComponent:()=>f});var n=r(4791),i=r(2618),o=r(7687),s=function(t,e,r,n){var i,o=arguments.length,s=o<3?e:null===n?n=Object.getOwnPropertyDescriptor(e,r):n;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)s=Reflect.decorate(t,e,r,n);else for(var a=t.length-1;a>=0;a--)(i=t[a])&&(s=(o<3?i(s):o>3?i(e,r,s):i(e,r))||s);return o>3&&s&&Object.defineProperty(e,r,s),s},a=function(t,e){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(t,e)};class l extends i.WF{constructor(){super(...arguments),this.strings=[],this.repetitions=1/0,this._generator=(0,o.nextStringsGenerator)("",this),this._currentTextValue=[]}static{this.styles=[i.AH`
			:host {
				display: block;
				font-family: monospace;
				unicode-bidi: isolate;
				font-size: 24px;
				line-height: 54px;
			}
		`]}firstUpdated(){this._generator=(0,o.nextStringsGenerator)(this.strings[0],this),this._currentTextValue=this.strings[0].split("").map((t=>({letter:t,classes:[]}))),this.splitText?.({context:this}),this.intervalCurrent=window.setTimeout((()=>{this.onInterval()}),this.interval)}disconnectedCallback(){this._generator.return(["",""]),window.clearTimeout(this.intervalCurrent)}onInterval(){const{done:t,value:e}=this._generator.next();t?(window.clearTimeout(this.intervalCurrent),this.intervalCurrent=void 0):this.triggerTextAnimation({context:this,fromText:e[0],toText:e[1]})}render(){return i.qy`${function*(t,e){if(void 0!==t){let e=0;for(const n of t)yield(r=n,e++,i.qy`<span class=${r.classes.join(" ")}>${r.letter}</span>`)}var r}(this._currentTextValue)}`}}s([(0,n.MZ)({type:Array}),a("design:type",Array)],l.prototype,"strings",void 0),s([(0,n.MZ)({type:Number}),a("design:type",Object)],l.prototype,"repetitions",void 0),s([(0,n.wk)(),a("design:type",Array)],l.prototype,"_currentTextValue",void 0);var c=r(5749),p=function(t,e,r,n){var i,o=arguments.length,s=o<3?e:null===n?n=Object.getOwnPropertyDescriptor(e,r):n;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)s=Reflect.decorate(t,e,r,n);else for(var a=t.length-1;a>=0;a--)(i=t[a])&&(s=(o<3?i(s):o>3?i(e,r,s):i(e,r))||s);return o>3&&s&&Object.defineProperty(e,r,s),s},u=function(t,e){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(t,e)};class f extends l{constructor(){super(...arguments),this.interval=2500,this.typingSpeed=75}triggerTextAnimation({context:t,fromText:e,toText:r}){const n=(0,c.createRebuildingTextSteps)(e,r);for(let e=0;e<n.length;e++)setTimeout((()=>{this._currentTextValue=n[e].filter(Boolean).map((t=>({letter:String(t),classes:[]}))),e===n.length-1&&setTimeout((()=>{t.onInterval()}),this.interval)}),this.typingSpeed*e)}}p([(0,n.MZ)({type:Number}),u("design:type",Object)],f.prototype,"interval",void 0),p([(0,n.MZ)({type:Number}),u("design:type",Object)],f.prototype,"typingSpeed",void 0)}}]);