require('../less/main-styles.less');

import './scripts/carousel';
require('../less/styles/carousel.less');
import './scripts/filtering';
require('../less/styles/filtering.less');
import './scripts/pagination';
require('../less/styles/pagination.less');
import './scripts/videoset';
require('../less/styles/videoset.less');
import './scripts/tabs';
require('../less/styles/tabs.less');
import './scripts/colorPicker';
require('../less/styles/colorPicker.less');
import './scripts/sidebar';
require('../less/styles/sidebar.less');
import './scripts/floating';
require('../less/styles/floating.less');
import './scripts/popup';
require('../less/styles/popup.less');
import './scripts/3dcarousel';
require('../less/styles/3dcarousel.less');
import './scripts/animatedCarousel';
require('../less/styles/animatedCarousel.less');
import './scripts/accordion';
import './scripts/typer';
import './scripts/rebuildingText';
import './scripts/cipheringText';
import './scripts/3dcarouselMenu';
import './scripts/zoomer';
import './scripts/stickyHeader';
import './scripts/upcomingWindow';
import './scripts/onePageScroll';
import './scripts/calculator';
import './scripts/screenInvert';
import './scripts/autocomplete';
import './scripts/imageComparsion';
import './scripts/toast';
import './scripts/gallery';
import './scripts/magnifier';
import './scripts/parallax';
import './scripts/countdown';
import './scripts/tableFiltering';
import './scripts/validation';
import './scripts/perspectiveCarousel';

import './mainControl';
