require('../less/main-styles.less');

import './scripts/carousel';
require('../less/styles/carousel.less');
import './scripts/filtering';
require('../less/styles/filtering.less');
import './scripts/pagination';
import './scripts/videoset';
import './scripts/tabs';
import './scripts/colorPicker';
import './scripts/sidebar';
require('../less/styles/sidebar.less');
import './scripts/floating';
import './scripts/popup';
import './scripts/3dcarousel';
import './scripts/animatedCarousel';
require('../less/styles/animatedCarousel.less');
import './scripts/accordion';
import './scripts/typer';
import './scripts/rebuildingText';
import './scripts/cipheringText';
import './scripts/3dcarouselMenu';
import './scripts/zoomer';
import './scripts/stickyHeader';
import './scripts/upcomingWindow';
import './scripts/onePageScroll';
import './scripts/calculator';
import './scripts/screenInvert';
import './scripts/autocomplete';
import './scripts/imageComparsion';
import './scripts/toast';
import './scripts/gallery';
import './scripts/magnifier';
import './scripts/parallax';
import './scripts/countdown';
import './scripts/tableFiltering';
import './scripts/validation';
import './scripts/perspectiveCarousel';

import './mainControl';
