require('../less/settings/colors.less');
require('../less/settings/fonts.less');

require('../less/main-styles.less');

import './scripts/carousel';
require('../less/styles/carousel.less');
import './scripts/filtering';
require('../less/styles/filtering.less');
import './scripts/pagination';
require('../less/styles/pagination.less');
import './scripts/videoset';
require('../less/styles/videoset.less');
import './scripts/tabs';
require('../less/styles/tabs.less');
import './scripts/colorPicker';
require('../less/styles/colorPicker.less');
import './scripts/sidebar';
require('../less/styles/sidebar.less');
import './scripts/floating';
require('../less/styles/floating.less');
import './scripts/popup';
require('../less/styles/popup.less');
import './scripts/3dcarousel';
require('../less/styles/3dcarousel.less');
import './scripts/animatedCarousel';
require('../less/styles/animatedCarousel.less');
import './scripts/accordion';
require('../less/styles/accordion.less');
import './scripts/typer';
require('../less/styles/typer.less');
import './scripts/rebuildingText';
import './scripts/cipheringText';
require('../less/styles/cipheringText.less');
import './scripts/3dcarouselMenu';
require('../less/styles/3dcarouselMenu.less');
import './scripts/zoomer';
require('../less/styles/zoomer.less');
import './scripts/stickyHeader';
require('../less/styles/stickyHeader.less');
import './scripts/upcomingWindow';
require('../less/styles/upcomingWindow.less');
import './scripts/onePageScroll';
require('../less/styles/onePageScroll.less');
import './scripts/calculator';
require('../less/styles/calculator.less');
import './scripts/screenInvert';
require('../less/styles/screenInvert.less');
import './scripts/autocomplete';
require('../less/styles/autocomplete.less');
import './scripts/imageComparsion';
require('../less/styles/imageComparsion.less');
import './scripts/toast';
require('../less/styles/toast.less');
import './scripts/gallery';
require('../less/styles/gallery.less');
import './scripts/magnifier';
require('../less/styles/magnifier.less');
import './scripts/parallax';
require('../less/styles/parallax.less');
import './scripts/countdown';
require('../less/styles/countdown.less');
import './scripts/tableFiltering';
require('../less/styles/tableFiltering.less');
import './scripts/validation';
require('../less/styles/validation.less');
import './scripts/perspectiveCarousel';
require('../less/styles/perspectiveCarousel.less');
import './scripts/customSelect';
require('../less/styles/customSelect.less');
import './scripts/registration';
require('../less/styles/registration.less');

import './mainControl';
